/**
 * Fixture — the example DSSE-signed TrustCertificate, decoded and mapped
 * into the camelCase DsseEnvelope/TrustCertificateStatement shape from
 * nota 18 §2.3.
 *
 * certificate.example.json is emitted by scripts/gen-example-trust-
 * certificate.py in real wire format: snake_case Statement fields, base64
 * payload, Ed25519 signature over the DSSE PAE (nota 02 §1.3). This module
 * decodes payload_b64 → JSON, then maps field names explicitly (run_id →
 * runId, domain_id → domainId, etc.) rather than a generic deep-camelcase
 * utility, per the brief — the mapping is small and the field list is
 * fixed by the frozen certificate contract (nota 02), so an explicit
 * mapping is more auditable than a generic recursive transform.
 *
 * No runtime schema validation here: this JSON is generated by our own
 * script and checked into the repo (not an external/untrusted API
 * response), so an explicit-mapping cast at this single boundary is
 * proportionate — a full validator would be speculative for a fixture we
 * fully control end-to-end.
 */

import rawEnvelopeJson from './certificate.example.json';
import type {
  AnchorKind,
  Attestation,
  DsseEnvelope,
  TrustCertificateStatement,
  Verdict
} from '../views/types';

interface RawAttestation {
  readonly verifier_id: string;
  readonly anchor_kind: string;
  readonly rung: number;
  readonly verdict: string;
  readonly method: string;
  readonly summary: string;
  readonly evidence: Record<string, unknown>;
}

interface RawStatement {
  readonly _type: string;
  readonly subject: readonly {
    readonly name: string;
    readonly digest: { readonly sha256: string };
  }[];
  readonly predicateType: string;
  readonly predicate: {
    readonly run_id: string;
    readonly actor: { readonly id: string; readonly kind: string; readonly domain_id: string };
    readonly aggregate_rung: number;
    readonly unanchored_steps: number;
    readonly attestations: readonly RawAttestation[];
    readonly policy_id: string;
    readonly issued_at: string;
  };
}

interface RawEnvelope {
  readonly payloadType: string;
  readonly payload: string; // base64
  readonly signatures: readonly { readonly keyid: string; readonly sig: string }[];
}

function decodeBase64Utf8(base64: string): string {
  const binary = atob(base64);
  const bytes = Uint8Array.from(binary, char => char.charCodeAt(0));
  return new TextDecoder('utf-8').decode(bytes);
}

function mapAttestation(raw: RawAttestation): Attestation {
  return {
    verifierId: raw.verifier_id,
    anchorKind: raw.anchor_kind as AnchorKind,
    rung: raw.rung,
    verdict: raw.verdict as Verdict,
    method: raw.method,
    summary: raw.summary,
    evidence: raw.evidence
  };
}

function mapStatement(raw: RawStatement): TrustCertificateStatement {
  return {
    _type: raw._type,
    subject: raw.subject,
    predicateType: raw.predicateType,
    predicate: {
      runId: raw.predicate.run_id,
      actor: {
        id: raw.predicate.actor.id,
        kind: raw.predicate.actor.kind,
        domainId: raw.predicate.actor.domain_id
      },
      aggregateRung: raw.predicate.aggregate_rung,
      unanchoredSteps: raw.predicate.unanchored_steps,
      attestations: raw.predicate.attestations.map(mapAttestation),
      policyId: raw.predicate.policy_id,
      issuedAt: raw.predicate.issued_at
    }
  };
}

function buildExampleCertificate(raw: RawEnvelope): DsseEnvelope {
  const decodedPayload = decodeBase64Utf8(raw.payload);
  const statement = JSON.parse(decodedPayload) as RawStatement;
  return {
    payloadType: raw.payloadType,
    payload: mapStatement(statement),
    signatures: raw.signatures
  };
}

export const EXAMPLE_CERTIFICATE: DsseEnvelope = buildExampleCertificate(rawEnvelopeJson);
