/**
 * Fixture — the example DSSE-signed TrustCertificate, decoded and mapped
 * into the camelCase DsseEnvelope/TrustCertificateStatement shape from
 * nota 18 §2.3 + freeze §7 (vocabulario clase+AL — reobra ET-9).
 *
 * certificate.example.json is emitted by scripts/gen-example-bundle.py in
 * real wire format (snake_case Statement fields, base64 payload, Ed25519
 * signature over the DSSE PAE) — the SAME auto-validated 7/7 bundle that
 * scripts/example-bundle.json carries, one single source. This module
 * decodes payload → JSON, then maps field names explicitly (run_id →
 * runId, titular_level → titularLevel, etc.) rather than a generic
 * deep-camelcase utility — the mapping is small and the field list is
 * fixed by the frozen certificate contract (freeze §7), so an explicit
 * mapping is more auditable than a generic recursive transform.
 *
 * No runtime schema validation here: this JSON is generated by our own
 * script and checked into the repo (not an external/untrusted API
 * response), so an explicit-mapping cast at this single boundary is
 * proportionate — a full validator would be speculative for a fixture we
 * fully control end-to-end. (Zod en las fronteras llega con F3 para los
 * payloads del gateway real.)
 */

import rawEnvelopeJson from './certificate.example.json';
import type {
  AssuranceLevel,
  CertificateAttestation,
  DsseEnvelope,
  TrustCertificateStatement,
  Verdict
} from '../views/types';

interface RawAttestation {
  readonly verifier_id: string;
  readonly verifier_class: string;
  readonly anchor_kind?: string;
  readonly level: string;
  readonly verdict: string;
  readonly independence_group: string;
  readonly claim_digest: string;
  readonly issued_at: string;
}

interface RawConclusion {
  readonly claim_digest: string;
  readonly canonical_statement: string;
  readonly scope: Readonly<Record<string, string>>;
  readonly verdict: string;
  readonly level: string;
  readonly claim_type?: string;
}

interface RawStatement {
  readonly _type: string;
  readonly subject: readonly {
    readonly name: string;
    readonly digest: { readonly sha256: string };
  }[];
  readonly predicateType: string;
  readonly predicate: {
    readonly run_id: string;
    readonly actor: string;
    readonly provenance_hash: string;
    readonly conclusions: readonly RawConclusion[];
    readonly titular_level: string;
    readonly assumptions: readonly {
      readonly statement: string;
      readonly ref?: { readonly name: string; readonly digest: string };
    }[];
    readonly deliverables: readonly {
      readonly artifact_ref: string;
      readonly digest: string;
    }[];
    readonly unanchored_steps: number;
    readonly policy_digest: string;
    readonly calculus_version: string;
    readonly valid_as_of: string;
    readonly revocation: string;
    readonly attestations: readonly RawAttestation[];
  };
}

interface RawEnvelope {
  readonly payloadType: string;
  readonly payload: string; // base64
  readonly signatures: readonly { readonly keyid: string; readonly sig: string }[];
}

function decodeBase64Utf8(base64: string): string {
  const binary = atob(base64);
  const bytes = Uint8Array.from(binary, char => char.charCodeAt(0));
  return new TextDecoder('utf-8').decode(bytes);
}

function mapAttestation(raw: RawAttestation): CertificateAttestation {
  return {
    verifierId: raw.verifier_id,
    verifierClass: raw.verifier_class,
    anchorKind: raw.anchor_kind,
    level: raw.level as AssuranceLevel,
    verdict: raw.verdict as Verdict,
    independenceGroup: raw.independence_group,
    claimDigest: raw.claim_digest,
    issuedAt: raw.issued_at
  };
}

function mapStatement(raw: RawStatement): TrustCertificateStatement {
  const { predicate } = raw;
  return {
    _type: raw._type,
    subject: raw.subject,
    predicateType: raw.predicateType,
    predicate: {
      runId: predicate.run_id,
      actor: predicate.actor,
      provenanceHash: predicate.provenance_hash,
      conclusions: predicate.conclusions.map(conclusion => ({
        claimDigest: conclusion.claim_digest,
        canonicalStatement: conclusion.canonical_statement,
        scope: conclusion.scope,
        verdict:
          conclusion.verdict as TrustCertificateStatement['predicate']['conclusions'][number]['verdict'],
        level: conclusion.level as AssuranceLevel,
        claimType: conclusion.claim_type
      })),
      titularLevel: predicate.titular_level as AssuranceLevel,
      assumptions: predicate.assumptions,
      deliverables: predicate.deliverables.map(deliverable => ({
        artifactRef: deliverable.artifact_ref,
        digest: deliverable.digest
      })),
      unanchoredSteps: predicate.unanchored_steps,
      policyDigest: predicate.policy_digest,
      calculusVersion: predicate.calculus_version,
      validAsOf: predicate.valid_as_of,
      revocation: predicate.revocation,
      attestations: predicate.attestations.map(mapAttestation)
    }
  };
}

function buildExampleCertificate(raw: RawEnvelope): DsseEnvelope {
  const decodedPayload = decodeBase64Utf8(raw.payload);
  const statement = JSON.parse(decodedPayload) as RawStatement;
  return {
    payloadType: raw.payloadType,
    payload: mapStatement(statement),
    rawPayload: JSON.parse(decodedPayload) as unknown,
    signatures: raw.signatures
  };
}

export const EXAMPLE_CERTIFICATE: DsseEnvelope = buildExampleCertificate(rawEnvelopeJson);

/**
 * El envelope wire tal cual (payload base64 + firma): lo que se descarga.
 * Un envelope mapeado a camelCase NO es verificable offline — los bytes del
 * payload son la fe del certificado (freeze §7).
 */
export const EXAMPLE_CERTIFICATE_WIRE: RawEnvelope = rawEnvelopeJson;
